# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineAnalysis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineAnalysis.setObjectName("lineAnalysis")
        self.gridLayout.addWidget(self.lineAnalysis, 6, 1, 1, 1)
        self.pushRun = QtWidgets.QPushButton(self.centralwidget)
        self.pushRun.setObjectName("pushRun")
        self.gridLayout.addWidget(self.pushRun, 6, 0, 1, 1)
        self.comboBatch = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBatch.sizePolicy().hasHeightForWidth())
        self.comboBatch.setSizePolicy(sizePolicy)
        self.comboBatch.setObjectName("comboBatch")
        self.gridLayout.addWidget(self.comboBatch, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineCell = QtWidgets.QLineEdit(self.centralwidget)
        self.lineCell.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineCell.setObjectName("lineCell")
        self.gridLayout.addWidget(self.lineCell, 2, 0, 1, 1)
        self.listModelname = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listModelname.sizePolicy().hasHeightForWidth())
        self.listModelname.setSizePolicy(sizePolicy)
        self.listModelname.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listModelname.setObjectName("listModelname")
        self.gridLayout.addWidget(self.listModelname, 3, 1, 1, 1)
        self.listCellid = QtWidgets.QListView(self.centralwidget)
        self.listCellid.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listCellid.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listCellid.setObjectName("listCellid")
        self.gridLayout.addWidget(self.listCellid, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineModelname = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineModelname.sizePolicy().hasHeightForWidth())
        self.lineModelname.setSizePolicy(sizePolicy)
        self.lineModelname.setObjectName("lineModelname")
        self.horizontalLayout.addWidget(self.lineModelname)
        self.pushUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.pushUpdate.setObjectName("pushUpdate")
        self.horizontalLayout.addWidget(self.pushUpdate)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 30))
        self.menubar.setObjectName("menubar")
        self.menuNEMS_DB_test = QtWidgets.QMenu(self.menubar)
        self.menuNEMS_DB_test.setObjectName("menuNEMS_DB_test")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuNEMS_DB_test.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushRun.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Model search"))
        self.label_3.setText(_translate("MainWindow", "Batch"))
        self.label_2.setText(_translate("MainWindow", "Cell search"))
        self.pushUpdate.setText(_translate("MainWindow", "Refresh"))
        self.menuNEMS_DB_test.setTitle(_translate("MainWindow", "&NEMS DB test"))

